sources: 
  include:
    - ../../../Sources/
  exclude:
    - ../../../Sources/Tuist/Dependencies/
templates:
  - ./template.stencil
output: 
  ../../../Sources/Tuist/ProjectDescriptionHelpers/CodeGeneration/ModuleNames.generated.swift